language: node_js
node_js: 
  - "12.16.1"
install:
  - "npm install"
before_script:
  - "npm run build"
  - "npm start &"
script:
  - "npm test"
env:
  global:
    - COVERALLS_PARALLEL=true
notifications:
  webhooks: https://coveralls.io/webhook
repo_token: i0bshm8x7XRl99K8kPtLCrU997YuJAphG