language: node_js
node_js: 
  - "12.16.1"
install:
  - "npm install"
   - npm install -g codecov
before_script:
  - "npm run build"
  - "npm start &"
script:
  - "npm test"
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov