language: node_js
node_js: 
  - "12.16.1"
install:
  - "npm install"
before_script:
  - "npm run build"
  - "npm start &"
script:
  - "npm test"
  - npm run lint
  - npm run coverage
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov --disable=gcov

sudo: required
env:
  global:
    - CC_TEST_REPORTER_ID=3ea1bf004c3fc4004876e0a7784bd21766f4eebc94adf83291908b872235d7af
